spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    serialization:
      indent_output: true

app:
  upload-dir: uploads

gcp:
  project-id: ${GCP_PROJECT_ID}
  bucket: ${GCS_BUCKET}

